name: ðŸ“… Schedule Dependencies Update
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

env:
  RENOVATE_BASE_DIR: ${{ github.workspace }}/.renovate
  NPM_CONFIG_CACHE: ${{ github.workspace }}/.npm-cache

jobs:
  dependency-update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm  
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24.13.0'

      - name: Cache Renovate cache directory
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: ${{ runner.os }}-renovate-cache-dir
          path: ${{ env.RENOVATE_BASE_DIR }}/cache

      - name: Read Renovate version
        run: echo "RENOVATE_VERSION=$(< .ci/renovate/.renovate-version)" >> $GITHUB_ENV

      - name: Cache NPM cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          key: renovate-${{ env.RENOVATE_VERSION }}
          path: ${{ env.NPM_CONFIG_CACHE }}

      - name: Run Renovate
        run: npx -y renovate@${{ env.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: debug
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/.ci/renovate/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_BASE_DIR: ${{ env.RENOVATE_BASE_DIR }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}