name: ðŸ“… Schedule Dependencies Update
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

env:
  RENOVATE_BASE_DIR: ${{ github.workspace }}/.renovate
  NPM_CONFIG_CACHE: ${{ github.workspace }}/.npm-cache

jobs:
  dependency-update:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: '24.12.0'

      - name: Cache Renovate cache directory
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          key: ${{ runner.os }}-renovate-cache-dir
          path: ${{ env.RENOVATE_BASE_DIR }}/cache

      - name: Read Renovate version
        run: echo "RENOVATE_VERSION=$(< .ci/renovate/.renovate-version)" >> $GITHUB_ENV

      - name: Cache NPM cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          key: renovate-${{ env.RENOVATE_VERSION }}
          path: ${{ env.NPM_CONFIG_CACHE }}

      - name: Run Renovate
        run: npx -y renovate@${{ env.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: debug
          RENOVATE_CONFIG_FILE: ${{ github.workspace }}/.ci/renovate/renovate.json
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_BASE_DIR: ${{ env.RENOVATE_BASE_DIR }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}